name: Build C++ Module

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/cpp/build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python info (debug)
        run: |
          python -V
          which python
          python -c "import sys, sysconfig; print('prefix=', sys.prefix); print('platlib=', sysconfig.get_paths().get('platlib'))"
          pip --version

      - name: Install system packages (build tools, OpenBLAS, python dev headers)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build pkg-config \
            python3-dev libpython3-dev python3-pip \
            libopenblas-dev liblapack-dev
          dpkg -l | sed -n '1,200p'

      - name: Upgrade pip and install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pybind11 xtensor-python numpy
          python -c "import pybind11, xtensor, xtensor_python, numpy; print('pybind11', pybind11.get_cmake_dir())"

      - name: Show CMake & compiler info (debug)
        run: |
          cmake --version
          gcc --version
          g++ --version

      - name: Prepare build dir
        run: |
          mkdir -p "${BUILD_DIR}"
          ls -la cpp || echo "Warning: 'cpp' directory not found"

      - name: Configure CMake
        run: |
          export PYTHON_EXECUTABLE="$(which python)"
          cmake -S cpp -B "${BUILD_DIR}" -DCMAKE_BUILD_TYPE=Release \
            -DPYTHON_EXECUTABLE="${PYTHON_EXECUTABLE}" \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build project with CMake
        run: |
          cmake --build "${BUILD_DIR}" --config Release -- -j$(nproc)

      - name: Generate pyi stubs (if script exists)
        run: |
          if [ -x "./generate_stubs.sh" ]; then
            export BUILD_DIR=${BUILD_DIR}
            export STUB_OUT=${{ github.workspace }}/cpp/stubs
            mkdir -p "$STUB_OUT"
            bash ./generate_stubs.sh
          else
            echo "No generate_stubs.sh found — skipping stubs generation"
          fi

      - name: List build outputs (debug)
        run: |
          echo "Contents of build dir:"
          ls -la "${BUILD_DIR}" || true
          echo "Contents of cpp:"
          ls -la cpp || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpp-build
          path: |
            ${{ github.workspace }}/cpp/build
            ${{ github.workspace }}/cpp/stubs
