name: CI - Build + Test (Ubuntu + Mamba)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          python-version: '3.11'
          miniconda-version: 'latest'
          mamba-version: '*'
          channels: conda-forge

      - name: Install all dependencies with Mamba
        run: |
          mamba install -y \
            cmake cxx-compiler numpy pybind11 scikit-learn pandas \
            xtensor xtensor-python xtensor-blas openblas

      - name: Configure & build with CMake
        run: |
          mkdir -p cpp/build
          cd cpp/build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -- -j2

      - name: Test Python bindings
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/cpp/build
          python -c "import mlcore_cpp; print('✅ Import successful!')"
