jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          # This is the most important dependency, providing Python.h for C++
          sudo apt-get install -y python3-dev
          python -m pip install --upgrade pip
          # Explicitly install numpy, as CMake often needs its headers
          pip install numpy
          # Install your project's other requirements
          pip install -r requirements.txt

      - name: Configure and build C++ extension
        run: |
          mkdir -p cpp/build
          cd cpp/build
          # REMOVED HINT: Let modern CMake auto-discover Python from the environment
          # set up by actions/setup-python. This is more reliable.
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Test Python bindings
        run: |
          # Add the build directory to Python's path to find the .so/.pyd file
          export PYTHONPATH=$PYTHONPATH:$(pwd)/cpp/build
          python -c "import sys; import mlcore_cpp; print('Import successful!')"
          # Then run your tests, e.g., pytest
