name: CI - Build + Test (Ubuntu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.26'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip python3-venv
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build C++ extension
        run: |
          mkdir -p cpp/build
          cd cpp/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$(which python)
          cmake --build . --config Release

      # Test Python bindings
      - name: Test Python bindings
        run: |
          # Add built module to PYTHONPATH
          python -c "import sys; sys.path.append('cpp/build'); import mlcore_cpp; print('Import successful!')"
          # pytest -q
