name: Build C++ Module

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/cpp/build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            python3.10-dev python3-pip \
            libopenblas-dev liblapack-dev

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install pybind11 xtensor-python

      - name: Configure CMake
        run: |
          mkdir -p $BUILD_DIR
          cmake -S cpp -B $BUILD_DIR -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build $BUILD_DIR --config Release -- -j$(nproc)

      - name: Generate stubs if exists
        run: |
          if [ -x "./generate_stubs.sh" ]; then
            mkdir -p cpp/stubs
            export BUILD_DIR=$BUILD_DIR
            export STUB_OUT=${{ github.workspace }}/cpp/stubs
            bash ./generate_stubs.sh
          else
            echo "No generate_stubs.sh found — skipping stubs"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cpp-build
          path: |
            cpp/build
            cpp/stubs
