name: CI - Build + Test (Ubuntu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          # This is the key dependency for C++ headers (Python.h)
          sudo apt-get install -y python3-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure and build C++ extension
        run: |
          mkdir -p cpp/build
          cd cpp/build

          # Get the Python executable path
          PY_EXECUTABLE=$(which python)
          echo "Using Python executable: $PY_EXECUTABLE"

          # Run CMake, providing the hint that the OLD FindPython module expects.
          # This matches what your CMakeLists.txt is likely using.
          cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE="$PY_EXECUTABLE"
          cmake --build . --config Release

      - name: Test Python bindings
        run: |
          # Add the build directory to PYTHONPATH so the module can be found
          export PYTHONPATH=$PYTHONPATH:$(pwd)/cpp/build
          python -c "import mlcore_cpp; print('Import successful!')"
