name: CI - Build + Test (Ubuntu + vcpkg)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git curl cmake python3-dev python3-pip python3-venv
          python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Clone and bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git $GITHUB_WORKSPACE/vcpkg
          $GITHUB_WORKSPACE/vcpkg/bootstrap-vcpkg.sh
          $GITHUB_WORKSPACE/vcpkg/vcpkg install xtensor xtensor-python xtensor-blas openblas:x64-linux

      - name: Configure & build C++ extension
        run: |
          mkdir -p cpp/build
          cd cpp/build

          PY_BIN=$(which python)
          NUMPY_INCLUDE=$(python -c "import numpy as np; print(np.get_include())")

          echo "Python executable: $PY_BIN"
          echo "NumPy include: $NUMPY_INCLUDE"

          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=x64-linux \
            -DPython3_EXECUTABLE="$PY_BIN" \
            -DNUMPY_INCLUDE_DIR="$NUMPY_INCLUDE"

          cmake --build . --config Release -- -j2

      - name: Smoke test - import built module
        run: |
          python -c "import sys; sys.path.append('cpp/build'); import mlcore_cpp; print('✅ Import successful!')"
