name: CI - Build + Test (Ubuntu + vcpkg)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git curl cmake python3-dev python3-pip python3-venv

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Bootstrap vcpkg
        run: |
          # clone vcpkg and bootstrap it
          git clone https://github.com/microsoft/vcpkg.git deps/vcpkg
          cd deps/vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics
          # install required packages into vcpkg
          ./vcpkg install pybind11 xtensor xtensor-python xtensor-blas openblas --triplet x64-linux
        shell: bash

      - name: Configure & build with CMake (using vcpkg)
        env:
          VCPKG_ROOT: ${{ github.workspace }}/deps/vcpkg
        run: |
          set -e
          mkdir -p cpp/build
          cd cpp/build

          # get python info
          PY_BIN=$(which python)
          PY_INCLUDE=$(python -c "import sysconfig; print(sysconfig.get_paths()['include'])")
          PY_LIB=$(python -c "import sysconfig, os; ld = sysconfig.get_config_var('LDLIBRARY'); libdir = sysconfig.get_config_var('LIBDIR'); print(os.path.join(libdir, ld) if ld and libdir else '')")
          NUMPY_INCLUDE=$(python -c "import numpy as np; print(np.get_include())")

          echo "Python: $PY_BIN"
          echo "Python include: $PY_INCLUDE"
          echo "Python lib: $PY_LIB"
          echo "NumPy include: $NUMPY_INCLUDE"

          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=x64-linux \
            -DPython_EXECUTABLE="$PY_BIN" \
            -DPython_INCLUDE_DIRS="$PY_INCLUDE" \
            -DPython_LIBRARIES="$PY_LIB" \
            -DNUMPY_INCLUDE_DIR="$NUMPY_INCLUDE"

          cmake --build . --config Release -- -j2
        shell: bash

      - name: Smoke test - import built module
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/cpp/build
          python -c "import mlcore_cpp; print('✅ Import successful!')"
